name: FastAPI - Basic Chek

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fastapi-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependência com Poetry
        run: poetry install --no-interaction --no-root

      - name: Rodar testes (placeholder)
        run: echo "Nenhum teste configurado ainda."

      - name: Build da imagem Docker
        run: docker build -t my-fastapi-app .
